### ISSUE TITLE
Put resulting data from more_data into memory

### ISSUE THREAD

**Issue by KeironO** [KeironO/pyvec#3]
@MiguelAngelRG suggested that to solve issues with low image quantity, that we produce new data. This is quite a normal with CNNs, as they can't tell the difference with data that has slightly been rotated.

I have implemented this in 91e4f2beba79d18e58274ffaa82cfcbedff9a28a, but as you can see it only writes the transformed files to the disk. 

I believe that it would be ideal to have this done in memory on runtime.

**Comment by MiguelAngelRG** [comment]
Hi Keiron,

Have you taken a look to the (Python Image Library)

http://effbot.org/imagingbook/introduction.htm

http://www.google.com/url?q=https://docs.python.org/2/c-api/string.html&sa=U&ved=0CC4QFjADahUKEwj2reP1qLDHAhWCvRoKHRF7AfU&sig2=Hd9SLMo3aFaD7W8XEVt6HQ&usg=AFQjCNGIQQ0KByVEj3TOE3D1ZRgjYnxX3g

http://simplecv-examples.readthedocs.org/en/latest/examples/basics.html

I am wondering if you would like a string in order to save all bytes from
the picture.

Kind regars.

Miguel Angel.

**Comment by KeironO** [comment]
Hi Miguel,

I have used PIL throughout the project, it's just I'm not entirely sure how I can get it to function with our currently existing codebase!

Thanks,

K.

**Comment by MiguelAngelRG** [comment]
Hi Keiron,

After having the conversation with you I was thinking that you just have
different ways to do that, as I suppose that you know:

1) Classes: https://docs.python.org/2/tutorial/classes.html
2) Byte arrays:
http://stackoverflow.com/questions/855191/how-big-can-a-python-array-get
(here you can see the maximum size that you could use in order to create an
array). Here you have the libraries
https://docs.python.org/2/library/array.html
3) External libraries like Python Image Library but If you want to create a
"standard" version of PyVec you should use the other solutions.

What do you think ?..

Kind regards,

Miguel Angel.

**Comment by KeironO** [comment]
And how can I load this in a similar way to the way I am currently loading data?

**Comment by MiguelAngelRG** [comment]
I have take a look of your code and I do not understand why do you want to
rotate the image?

And the other thing that I do not understand is do you want to put 5000
images on memory in order to
do no create a intermediate files (temp files)?  This is the goal that you
want to achieve ?

**Comment by KeironO** [comment]
Upon consideration, we no longer require this.
